repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
    -   id: check-manifest
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
