language: python

env:
  - ENV=travis

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

os:
  - linux

install:
  - pip install --upgrade pip
  - pip install -e .[dev]

script:
  - pytest

after_success:
  - codecov

branches:
  only:
    - main
